version: '3.9'

services:
  rabbit:
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://127.0.0.1:5672']
      interval: 30s
      timeout: 10s
      retries: 5
    image: rabbitmq:3-management
    network_mode: "host"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  apybara:
    build:
      context: ./
      dockerfile: ./beanstalk/apybara/Dockerfile
    depends_on:
      - rabbit
    network_mode: "host"

  faker:
    build:
      context: ./
      dockerfile: ./beanstalk/faker/Dockerfile
    depends_on:
      - rabbit
    network_mode: "host"
