version: '3.9'

services:
  rabbit:
    image: rabbitmq:3-management
    networks:
      - apybara-net
    ports:
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  apybara:
    build:
      context: ./
      dockerfile: ./beanstalk/apybara/Dockerfile
    depends_on:
      - rabbit
    networks:
      - apybara-net
    ports:
      - '80:3000'

  faker:
    build:
      context: ./
      dockerfile: ./beanstalk/faker/Dockerfile
    depends_on:
      - rabbit
    networks:
      - apybara-net

networks:
  apybara-net:
    driver: bridge
